test/Makefile: add 'run' command
Usage: make -C test run

Signed-off-by: Leesoo Ahn <lsahn@ooseel.net>

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -1,15 +1,23 @@
 CC = g++
-CXXFLAGS := -I../include
+CXXFLAGS := -g -Og
+CXXFLAGS += -I../include
 CXXFLAGS += -fpermissive
 
 TARGETS := \
+	test-vector \
 	test-fixed-vector
 
 all: clean $(TARGETS)
 
 %: %.cpp
 	$(CC) $(CXXFLAGS) $< -o $@ $(LIBS)
-	$(shell pwd)/$@
+
+run: all
+	@for ITEM in $(TARGETS); do \
+		$(shell pwd)/$$ITEM; \
+		[ $$? -eq 0 ] && { echo "[PASS] - $$ITEM"; } \
+		              || { echo ">> [FAIL] - $$ITEM"; }; \
+	done
 
 clean:
 	@rm -rf $(TARGETS)
